# Generated by Django 2.2.12 on 2022-04-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bangunruang',
            name='jumlah',
            field=models.IntegerField(null=True),
        ),
    ]
