# Generated by Django 2.2.12 on 2022-04-28 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0002_bangunruang_jumlah'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bangunruang',
            new_name='bangundatar',
        ),
    ]
